package cn.bravolinks.erp.crm.server.dao.xzkh;

import cn.bravolinks.erp.crm.server.model.xzkh.BoCrmIndclientbusYlm;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface BoCrmIndclientbusYlmDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insert(BoCrmIndclientbusYlm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insertSelective(BoCrmIndclientbusYlm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    BoCrmIndclientbusYlm selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKeySelective(BoCrmIndclientbusYlm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YLM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKey(BoCrmIndclientbusYlm record);

    List<BoCrmIndclientbusYlm> selectByBindid(Integer bindid);
}