package cn.bravolinks.erp.crm.server.dao.xzkh;

import cn.bravolinks.erp.crm.server.model.xzkh.BoCrmClientbusOreg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface BoCrmClientbusOregDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    int insert(BoCrmClientbusOreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    int insertSelective(BoCrmClientbusOreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    BoCrmClientbusOreg selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    int updateByPrimaryKeySelective(BoCrmClientbusOreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENTBUS_OREG
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    int updateByPrimaryKey(BoCrmClientbusOreg record);

    List<BoCrmClientbusOreg> selectByBindid(Integer bindid);
}