package cn.bravolinks.erp.crm.server.dao.xzkh;

import cn.bravolinks.erp.crm.server.model.xzkh.BoCrmIndclientbusYtr;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface BoCrmIndclientbusYtrDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insert(BoCrmIndclientbusYtr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insertSelective(BoCrmIndclientbusYtr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    BoCrmIndclientbusYtr selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKeySelective(BoCrmIndclientbusYtr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YTR
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKey(BoCrmIndclientbusYtr record);

    List<BoCrmIndclientbusYtr> selectByBindid(Integer bindid);
}