package cn.bravolinks.erp.crm.server.dao.xzkh;

import cn.bravolinks.erp.crm.server.model.xzkh.BoCrmIndclientbusYee;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface BoCrmIndclientbusYeeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insert(BoCrmIndclientbusYee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int insertSelective(BoCrmIndclientbusYee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    BoCrmIndclientbusYee selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKeySelective(BoCrmIndclientbusYee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_INDCLIENTBUS_YEE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    int updateByPrimaryKey(BoCrmIndclientbusYee record);

    List<BoCrmIndclientbusYee> selectByBindid(Integer bindid);
}