package cn.bravolinks.erp.crm.server.dao.xzkh;

import cn.bravolinks.erp.crm.server.model.xzkh.BoCrmClientLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.Map;
@Mapper
public interface BoCrmClientLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    int insert(BoCrmClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    int insertSelective(BoCrmClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    BoCrmClientLog selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    int updateByPrimaryKeySelective(BoCrmClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BO_CRM_CLIENT_LOG
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    int updateByPrimaryKey(BoCrmClientLog record);

    Map<String, Object> selectInfoByUser(String userid);
}