package cn.bravolinks.erp.crm.server.model.xzkh;

import java.math.BigDecimal;
import java.util.Date;

public class BoCrmIndclientbusP {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.LX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bmxzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.GJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object gjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.MZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object mzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.XBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.HYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object hyzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zjxydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.QTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object qtshjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.IFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ifdam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.CDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object cdggjdq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.RYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ryztdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.JSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object jsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.XRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xrzdwbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.XRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xrzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.DRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object drzw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object dwdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.EMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.JCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object jcfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.SJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object sjgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zjlxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.ZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.SJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object sjlydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bmndylxrdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.FJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object fj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.TX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object tx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.MP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object mp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.JTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer jtwlkh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YLX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YKHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ykhbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YKHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ykhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YBMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ybmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YBMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ybmxzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YYW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yyw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YGJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ygjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YMZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ymzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YXBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yxbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YCSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date ycsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YHYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yhyzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yzjxydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yzzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YQTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yqtshjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YIFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yifdam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YCDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ycdggjdq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YRYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yryztdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YJSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yjsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yzwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YXRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yxrzdwbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YXRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yxrzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YDRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ydrzw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YDWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ydwdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YYDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yyddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YEMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YJCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yjcfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YSJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ysjgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yzjlxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yzjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YSJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ysjlydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YBMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ybmndylxrdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YBZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YFJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object yfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YTX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ytx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YMP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ymp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YJTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer yjtwlkh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.LYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private BigDecimal lyxqys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YLYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private BigDecimal ylyxqys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.WHLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object whlxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.DAID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object daid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.TZZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object tzzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.LXRBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object lxrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.BMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YBMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ybmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHJLZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khjlzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHJLXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khjlxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YGSSTLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ygsstldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.DJSM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object djsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHJLSSBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khjlssbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.KHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object khdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.LXRBINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object lxrbindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_P.YKHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ykhdj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ID
     *
     * @param id the value for BO_CRM_INDCLIENTBUS_P.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ORGNO
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ORGNO
     *
     * @param orgno the value for BO_CRM_INDCLIENTBUS_P.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BINDID
     *
     * @param bindid the value for BO_CRM_INDCLIENTBUS_P.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.CREATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.CREATEDATE
     *
     * @param createdate the value for BO_CRM_INDCLIENTBUS_P.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.CREATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.CREATEUSER
     *
     * @param createuser the value for BO_CRM_INDCLIENTBUS_P.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.UPDATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_INDCLIENTBUS_P.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.UPDATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_INDCLIENTBUS_P.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_INDCLIENTBUS_P.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_INDCLIENTBUS_P.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ISEND
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ISEND
     *
     * @param isend the value for BO_CRM_INDCLIENTBUS_P.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.LX
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.LX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.LX
     *
     * @param lx the value for BO_CRM_INDCLIENTBUS_P.LX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLx(Object lx) {
        this.lx = lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhbh() {
        return khbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHBH
     *
     * @param khbh the value for BO_CRM_INDCLIENTBUS_P.KHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhbh(Object khbh) {
        this.khbh = khbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHMC
     *
     * @param khmc the value for BO_CRM_INDCLIENTBUS_P.KHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhmc(Object khmc) {
        this.khmc = khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BMMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BMMC
     *
     * @param bmmc the value for BO_CRM_INDCLIENTBUS_P.BMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBmmc(Object bmmc) {
        this.bmmc = bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BMXZDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBmxzdm() {
        return bmxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BMXZDM
     *
     * @param bmxzdm the value for BO_CRM_INDCLIENTBUS_P.BMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBmxzdm(Object bmxzdm) {
        this.bmxzdm = bmxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.XM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.XM
     *
     * @param xm the value for BO_CRM_INDCLIENTBUS_P.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXm(Object xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYw() {
        return yw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YW
     *
     * @param yw the value for BO_CRM_INDCLIENTBUS_P.YW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYw(Object yw) {
        this.yw = yw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.GJDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.GJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getGjdm() {
        return gjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.GJDM
     *
     * @param gjdm the value for BO_CRM_INDCLIENTBUS_P.GJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setGjdm(Object gjdm) {
        this.gjdm = gjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.MZDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.MZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.MZDM
     *
     * @param mzdm the value for BO_CRM_INDCLIENTBUS_P.MZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setMzdm(Object mzdm) {
        this.mzdm = mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.XBDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.XBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXbdm() {
        return xbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.XBDM
     *
     * @param xbdm the value for BO_CRM_INDCLIENTBUS_P.XBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXbdm(Object xbdm) {
        this.xbdm = xbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.CSRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.CSRQ
     *
     * @param csrq the value for BO_CRM_INDCLIENTBUS_P.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.HYZKDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.HYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getHyzkdm() {
        return hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.HYZKDM
     *
     * @param hyzkdm the value for BO_CRM_INDCLIENTBUS_P.HYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setHyzkdm(Object hyzkdm) {
        this.hyzkdm = hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ZJXYDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZjxydm() {
        return zjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ZJXYDM
     *
     * @param zjxydm the value for BO_CRM_INDCLIENTBUS_P.ZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZjxydm(Object zjxydm) {
        this.zjxydm = zjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ZZMMDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZzmmdm() {
        return zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ZZMMDM
     *
     * @param zzmmdm the value for BO_CRM_INDCLIENTBUS_P.ZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZzmmdm(Object zzmmdm) {
        this.zzmmdm = zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.QTSHJS
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.QTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getQtshjs() {
        return qtshjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.QTSHJS
     *
     * @param qtshjs the value for BO_CRM_INDCLIENTBUS_P.QTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setQtshjs(Object qtshjs) {
        this.qtshjs = qtshjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.IFDAM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.IFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getIfdam() {
        return ifdam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.IFDAM
     *
     * @param ifdam the value for BO_CRM_INDCLIENTBUS_P.IFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIfdam(Object ifdam) {
        this.ifdam = ifdam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.CDGGJDQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.CDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCdggjdq() {
        return cdggjdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.CDGGJDQ
     *
     * @param cdggjdq the value for BO_CRM_INDCLIENTBUS_P.CDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCdggjdq(Object cdggjdq) {
        this.cdggjdq = cdggjdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.RYZTDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.RYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getRyztdm() {
        return ryztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.RYZTDM
     *
     * @param ryztdm the value for BO_CRM_INDCLIENTBUS_P.RYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setRyztdm(Object ryztdm) {
        this.ryztdm = ryztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.JSDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.JSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getJsdm() {
        return jsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.JSDM
     *
     * @param jsdm the value for BO_CRM_INDCLIENTBUS_P.JSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setJsdm(Object jsdm) {
        this.jsdm = jsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ZWMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZwmc() {
        return zwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ZWMC
     *
     * @param zwmc the value for BO_CRM_INDCLIENTBUS_P.ZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZwmc(Object zwmc) {
        this.zwmc = zwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.XRZDWBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.XRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXrzdwbh() {
        return xrzdwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.XRZDWBH
     *
     * @param xrzdwbh the value for BO_CRM_INDCLIENTBUS_P.XRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXrzdwbh(Object xrzdwbh) {
        this.xrzdwbh = xrzdwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.XRZDW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.XRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXrzdw() {
        return xrzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.XRZDW
     *
     * @param xrzdw the value for BO_CRM_INDCLIENTBUS_P.XRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXrzdw(Object xrzdw) {
        this.xrzdw = xrzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.DRZW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.DRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDrzw() {
        return drzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.DRZW
     *
     * @param drzw the value for BO_CRM_INDCLIENTBUS_P.DRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDrzw(Object drzw) {
        this.drzw = drzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.DWDH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDwdh() {
        return dwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.DWDH
     *
     * @param dwdh the value for BO_CRM_INDCLIENTBUS_P.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDwdh(Object dwdh) {
        this.dwdh = dwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YDDH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYddh() {
        return yddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YDDH
     *
     * @param yddh the value for BO_CRM_INDCLIENTBUS_P.YDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYddh(Object yddh) {
        this.yddh = yddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.EMAIL
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.EMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.EMAIL
     *
     * @param email the value for BO_CRM_INDCLIENTBUS_P.EMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setEmail(Object email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.JCFG
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.JCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getJcfg() {
        return jcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.JCFG
     *
     * @param jcfg the value for BO_CRM_INDCLIENTBUS_P.JCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setJcfg(Object jcfg) {
        this.jcfg = jcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.SJGJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.SJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getSjgj() {
        return sjgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.SJGJ
     *
     * @param sjgj the value for BO_CRM_INDCLIENTBUS_P.SJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setSjgj(Object sjgj) {
        this.sjgj = sjgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ZJLXDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZjlxdm() {
        return zjlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ZJLXDM
     *
     * @param zjlxdm the value for BO_CRM_INDCLIENTBUS_P.ZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZjlxdm(Object zjlxdm) {
        this.zjlxdm = zjlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.ZJH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.ZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZjh() {
        return zjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.ZJH
     *
     * @param zjh the value for BO_CRM_INDCLIENTBUS_P.ZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZjh(Object zjh) {
        this.zjh = zjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.SJLYDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.SJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getSjlydm() {
        return sjlydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.SJLYDM
     *
     * @param sjlydm the value for BO_CRM_INDCLIENTBUS_P.SJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setSjlydm(Object sjlydm) {
        this.sjlydm = sjlydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BMNDYLXRDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBmndylxrdm() {
        return bmndylxrdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BMNDYLXRDM
     *
     * @param bmndylxrdm the value for BO_CRM_INDCLIENTBUS_P.BMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBmndylxrdm(Object bmndylxrdm) {
        this.bmndylxrdm = bmndylxrdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BZ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BZ
     *
     * @param bz the value for BO_CRM_INDCLIENTBUS_P.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBz(Object bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.FJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.FJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getFj() {
        return fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.FJ
     *
     * @param fj the value for BO_CRM_INDCLIENTBUS_P.FJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setFj(Object fj) {
        this.fj = fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.TX
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.TX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getTx() {
        return tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.TX
     *
     * @param tx the value for BO_CRM_INDCLIENTBUS_P.TX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setTx(Object tx) {
        this.tx = tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.MP
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.MP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.MP
     *
     * @param mp the value for BO_CRM_INDCLIENTBUS_P.MP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setMp(Object mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.JTWLKH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.JTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getJtwlkh() {
        return jtwlkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.JTWLKH
     *
     * @param jtwlkh the value for BO_CRM_INDCLIENTBUS_P.JTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setJtwlkh(Integer jtwlkh) {
        this.jtwlkh = jtwlkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YLX
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YLX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYlx() {
        return ylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YLX
     *
     * @param ylx the value for BO_CRM_INDCLIENTBUS_P.YLX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYlx(Object ylx) {
        this.ylx = ylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YKHBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YKHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYkhbh() {
        return ykhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YKHBH
     *
     * @param ykhbh the value for BO_CRM_INDCLIENTBUS_P.YKHBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYkhbh(Object ykhbh) {
        this.ykhbh = ykhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YKHMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YKHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYkhmc() {
        return ykhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YKHMC
     *
     * @param ykhmc the value for BO_CRM_INDCLIENTBUS_P.YKHMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYkhmc(Object ykhmc) {
        this.ykhmc = ykhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YBMMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YBMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYbmmc() {
        return ybmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YBMMC
     *
     * @param ybmmc the value for BO_CRM_INDCLIENTBUS_P.YBMMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYbmmc(Object ybmmc) {
        this.ybmmc = ybmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YBMXZDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YBMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYbmxzdm() {
        return ybmxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YBMXZDM
     *
     * @param ybmxzdm the value for BO_CRM_INDCLIENTBUS_P.YBMXZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYbmxzdm(Object ybmxzdm) {
        this.ybmxzdm = ybmxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YXM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYxm() {
        return yxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YXM
     *
     * @param yxm the value for BO_CRM_INDCLIENTBUS_P.YXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYxm(Object yxm) {
        this.yxm = yxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YYW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YYW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYyw() {
        return yyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YYW
     *
     * @param yyw the value for BO_CRM_INDCLIENTBUS_P.YYW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYyw(Object yyw) {
        this.yyw = yyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YGJDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YGJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYgjdm() {
        return ygjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YGJDM
     *
     * @param ygjdm the value for BO_CRM_INDCLIENTBUS_P.YGJDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYgjdm(Object ygjdm) {
        this.ygjdm = ygjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YMZDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YMZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYmzdm() {
        return ymzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YMZDM
     *
     * @param ymzdm the value for BO_CRM_INDCLIENTBUS_P.YMZDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYmzdm(Object ymzdm) {
        this.ymzdm = ymzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YXBDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YXBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYxbdm() {
        return yxbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YXBDM
     *
     * @param yxbdm the value for BO_CRM_INDCLIENTBUS_P.YXBDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYxbdm(Object yxbdm) {
        this.yxbdm = yxbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YCSRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YCSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getYcsrq() {
        return ycsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YCSRQ
     *
     * @param ycsrq the value for BO_CRM_INDCLIENTBUS_P.YCSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYcsrq(Date ycsrq) {
        this.ycsrq = ycsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YHYZKDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YHYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYhyzkdm() {
        return yhyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YHYZKDM
     *
     * @param yhyzkdm the value for BO_CRM_INDCLIENTBUS_P.YHYZKDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYhyzkdm(Object yhyzkdm) {
        this.yhyzkdm = yhyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YZJXYDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYzjxydm() {
        return yzjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YZJXYDM
     *
     * @param yzjxydm the value for BO_CRM_INDCLIENTBUS_P.YZJXYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYzjxydm(Object yzjxydm) {
        this.yzjxydm = yzjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YZZMMDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYzzmmdm() {
        return yzzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YZZMMDM
     *
     * @param yzzmmdm the value for BO_CRM_INDCLIENTBUS_P.YZZMMDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYzzmmdm(Object yzzmmdm) {
        this.yzzmmdm = yzzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YQTSHJS
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YQTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYqtshjs() {
        return yqtshjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YQTSHJS
     *
     * @param yqtshjs the value for BO_CRM_INDCLIENTBUS_P.YQTSHJS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYqtshjs(Object yqtshjs) {
        this.yqtshjs = yqtshjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YIFDAM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YIFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYifdam() {
        return yifdam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YIFDAM
     *
     * @param yifdam the value for BO_CRM_INDCLIENTBUS_P.YIFDAM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYifdam(Object yifdam) {
        this.yifdam = yifdam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YCDGGJDQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YCDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYcdggjdq() {
        return ycdggjdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YCDGGJDQ
     *
     * @param ycdggjdq the value for BO_CRM_INDCLIENTBUS_P.YCDGGJDQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYcdggjdq(Object ycdggjdq) {
        this.ycdggjdq = ycdggjdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YRYZTDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YRYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYryztdm() {
        return yryztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YRYZTDM
     *
     * @param yryztdm the value for BO_CRM_INDCLIENTBUS_P.YRYZTDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYryztdm(Object yryztdm) {
        this.yryztdm = yryztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YJSDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YJSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYjsdm() {
        return yjsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YJSDM
     *
     * @param yjsdm the value for BO_CRM_INDCLIENTBUS_P.YJSDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYjsdm(Object yjsdm) {
        this.yjsdm = yjsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YZWMC
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYzwmc() {
        return yzwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YZWMC
     *
     * @param yzwmc the value for BO_CRM_INDCLIENTBUS_P.YZWMC
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYzwmc(Object yzwmc) {
        this.yzwmc = yzwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YXRZDWBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YXRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYxrzdwbh() {
        return yxrzdwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YXRZDWBH
     *
     * @param yxrzdwbh the value for BO_CRM_INDCLIENTBUS_P.YXRZDWBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYxrzdwbh(Object yxrzdwbh) {
        this.yxrzdwbh = yxrzdwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YXRZDW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YXRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYxrzdw() {
        return yxrzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YXRZDW
     *
     * @param yxrzdw the value for BO_CRM_INDCLIENTBUS_P.YXRZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYxrzdw(Object yxrzdw) {
        this.yxrzdw = yxrzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YDRZW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YDRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYdrzw() {
        return ydrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YDRZW
     *
     * @param ydrzw the value for BO_CRM_INDCLIENTBUS_P.YDRZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYdrzw(Object ydrzw) {
        this.ydrzw = ydrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YDWDH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YDWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYdwdh() {
        return ydwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YDWDH
     *
     * @param ydwdh the value for BO_CRM_INDCLIENTBUS_P.YDWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYdwdh(Object ydwdh) {
        this.ydwdh = ydwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YYDDH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YYDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYyddh() {
        return yyddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YYDDH
     *
     * @param yyddh the value for BO_CRM_INDCLIENTBUS_P.YYDDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYyddh(Object yyddh) {
        this.yyddh = yyddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YEMAIL
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YEMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYemail() {
        return yemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YEMAIL
     *
     * @param yemail the value for BO_CRM_INDCLIENTBUS_P.YEMAIL
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYemail(Object yemail) {
        this.yemail = yemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YJCFG
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YJCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYjcfg() {
        return yjcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YJCFG
     *
     * @param yjcfg the value for BO_CRM_INDCLIENTBUS_P.YJCFG
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYjcfg(Object yjcfg) {
        this.yjcfg = yjcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YSJGJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YSJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYsjgj() {
        return ysjgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YSJGJ
     *
     * @param ysjgj the value for BO_CRM_INDCLIENTBUS_P.YSJGJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYsjgj(Object ysjgj) {
        this.ysjgj = ysjgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YZJLXDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYzjlxdm() {
        return yzjlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YZJLXDM
     *
     * @param yzjlxdm the value for BO_CRM_INDCLIENTBUS_P.YZJLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYzjlxdm(Object yzjlxdm) {
        this.yzjlxdm = yzjlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YZJH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYzjh() {
        return yzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YZJH
     *
     * @param yzjh the value for BO_CRM_INDCLIENTBUS_P.YZJH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYzjh(Object yzjh) {
        this.yzjh = yzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YSJLYDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YSJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYsjlydm() {
        return ysjlydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YSJLYDM
     *
     * @param ysjlydm the value for BO_CRM_INDCLIENTBUS_P.YSJLYDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYsjlydm(Object ysjlydm) {
        this.ysjlydm = ysjlydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YBMNDYLXRDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YBMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYbmndylxrdm() {
        return ybmndylxrdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YBMNDYLXRDM
     *
     * @param ybmndylxrdm the value for BO_CRM_INDCLIENTBUS_P.YBMNDYLXRDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYbmndylxrdm(Object ybmndylxrdm) {
        this.ybmndylxrdm = ybmndylxrdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YBZ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YBZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYbz() {
        return ybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YBZ
     *
     * @param ybz the value for BO_CRM_INDCLIENTBUS_P.YBZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYbz(Object ybz) {
        this.ybz = ybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YFJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YFJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYfj() {
        return yfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YFJ
     *
     * @param yfj the value for BO_CRM_INDCLIENTBUS_P.YFJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYfj(Object yfj) {
        this.yfj = yfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YTX
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YTX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYtx() {
        return ytx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YTX
     *
     * @param ytx the value for BO_CRM_INDCLIENTBUS_P.YTX
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYtx(Object ytx) {
        this.ytx = ytx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YMP
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YMP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYmp() {
        return ymp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YMP
     *
     * @param ymp the value for BO_CRM_INDCLIENTBUS_P.YMP
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYmp(Object ymp) {
        this.ymp = ymp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YJTWLKH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YJTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getYjtwlkh() {
        return yjtwlkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YJTWLKH
     *
     * @param yjtwlkh the value for BO_CRM_INDCLIENTBUS_P.YJTWLKH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYjtwlkh(Integer yjtwlkh) {
        this.yjtwlkh = yjtwlkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.LYXQYS
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.LYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public BigDecimal getLyxqys() {
        return lyxqys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.LYXQYS
     *
     * @param lyxqys the value for BO_CRM_INDCLIENTBUS_P.LYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLyxqys(BigDecimal lyxqys) {
        this.lyxqys = lyxqys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YLYXQYS
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YLYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public BigDecimal getYlyxqys() {
        return ylyxqys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YLYXQYS
     *
     * @param ylyxqys the value for BO_CRM_INDCLIENTBUS_P.YLYXQYS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYlyxqys(BigDecimal ylyxqys) {
        this.ylyxqys = ylyxqys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.WHLXDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.WHLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getWhlxdm() {
        return whlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.WHLXDM
     *
     * @param whlxdm the value for BO_CRM_INDCLIENTBUS_P.WHLXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWhlxdm(Object whlxdm) {
        this.whlxdm = whlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.DAID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.DAID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDaid() {
        return daid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.DAID
     *
     * @param daid the value for BO_CRM_INDCLIENTBUS_P.DAID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDaid(Object daid) {
        this.daid = daid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.TZZH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.TZZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getTzzh() {
        return tzzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.TZZH
     *
     * @param tzzh the value for BO_CRM_INDCLIENTBUS_P.TZZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setTzzh(Object tzzh) {
        this.tzzh = tzzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.LXRBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.LXRBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getLxrbh() {
        return lxrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.LXRBH
     *
     * @param lxrbh the value for BO_CRM_INDCLIENTBUS_P.LXRBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLxrbh(Object lxrbh) {
        this.lxrbh = lxrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.BMBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.BMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBmbh() {
        return bmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.BMBH
     *
     * @param bmbh the value for BO_CRM_INDCLIENTBUS_P.BMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBmbh(Object bmbh) {
        this.bmbh = bmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YBMBH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YBMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYbmbh() {
        return ybmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YBMBH
     *
     * @param ybmbh the value for BO_CRM_INDCLIENTBUS_P.YBMBH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYbmbh(Object ybmbh) {
        this.ybmbh = ybmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLZH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHJLZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhjlzh() {
        return khjlzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLZH
     *
     * @param khjlzh the value for BO_CRM_INDCLIENTBUS_P.KHJLZH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhjlzh(Object khjlzh) {
        this.khjlzh = khjlzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLXM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHJLXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhjlxm() {
        return khjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLXM
     *
     * @param khjlxm the value for BO_CRM_INDCLIENTBUS_P.KHJLXM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhjlxm(Object khjlxm) {
        this.khjlxm = khjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YGSSTLDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YGSSTLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYgsstldm() {
        return ygsstldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YGSSTLDM
     *
     * @param ygsstldm the value for BO_CRM_INDCLIENTBUS_P.YGSSTLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYgsstldm(Object ygsstldm) {
        this.ygsstldm = ygsstldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.DJSM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.DJSM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDjsm() {
        return djsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.DJSM
     *
     * @param djsm the value for BO_CRM_INDCLIENTBUS_P.DJSM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDjsm(Object djsm) {
        this.djsm = djsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLSSBM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHJLSSBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhjlssbm() {
        return khjlssbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHJLSSBM
     *
     * @param khjlssbm the value for BO_CRM_INDCLIENTBUS_P.KHJLSSBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhjlssbm(Object khjlssbm) {
        this.khjlssbm = khjlssbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.KHDJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.KHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getKhdj() {
        return khdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.KHDJ
     *
     * @param khdj the value for BO_CRM_INDCLIENTBUS_P.KHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setKhdj(Object khdj) {
        this.khdj = khdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.LXRBINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.LXRBINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getLxrbindid() {
        return lxrbindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.LXRBINDID
     *
     * @param lxrbindid the value for BO_CRM_INDCLIENTBUS_P.LXRBINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLxrbindid(Object lxrbindid) {
        this.lxrbindid = lxrbindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_P.YKHDJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_P.YKHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getYkhdj() {
        return ykhdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_P.YKHDJ
     *
     * @param ykhdj the value for BO_CRM_INDCLIENTBUS_P.YKHDJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setYkhdj(Object ykhdj) {
        this.ykhdj = ykhdj;
    }
}