package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmIndclientbusYhb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.XQAHFLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xqahfldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YHB.MS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object ms;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.ID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.ID
     *
     * @param id the value for BO_CRM_INDCLIENTBUS_YHB.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.ORGNO
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.ORGNO
     *
     * @param orgno the value for BO_CRM_INDCLIENTBUS_YHB.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.BINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.BINDID
     *
     * @param bindid the value for BO_CRM_INDCLIENTBUS_YHB.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.CREATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.CREATEDATE
     *
     * @param createdate the value for BO_CRM_INDCLIENTBUS_YHB.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.CREATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.CREATEUSER
     *
     * @param createuser the value for BO_CRM_INDCLIENTBUS_YHB.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_INDCLIENTBUS_YHB.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_INDCLIENTBUS_YHB.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_INDCLIENTBUS_YHB.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_INDCLIENTBUS_YHB.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.ISEND
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.ISEND
     *
     * @param isend the value for BO_CRM_INDCLIENTBUS_YHB.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.XQAHFLDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.XQAHFLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXqahfldm() {
        return xqahfldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.XQAHFLDM
     *
     * @param xqahfldm the value for BO_CRM_INDCLIENTBUS_YHB.XQAHFLDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXqahfldm(Object xqahfldm) {
        this.xqahfldm = xqahfldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YHB.MS
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YHB.MS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getMs() {
        return ms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YHB.MS
     *
     * @param ms the value for BO_CRM_INDCLIENTBUS_YHB.MS
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setMs(Object ms) {
        this.ms = ms;
    }
}