package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmClientLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.ID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.ORGNO
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.BINDID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.CREATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.CREATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.UPDATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.UPDATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.WORKFLOWID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.WORKFLOWSTEPID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.ISEND
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.GSID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object gsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.GSDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object gsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.GSMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object gsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.BMID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object bmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.BMMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.CZRZH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object czrzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.CZRXM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object czrxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.KHBH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object khbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.KHMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object khmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.WHSJ
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Date whsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENT_LOG.WHLXDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    private Object whlxdm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.ID
     *
     * @return the value of BO_CRM_CLIENT_LOG.ID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.ID
     *
     * @param id the value for BO_CRM_CLIENT_LOG.ID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.ORGNO
     *
     * @return the value of BO_CRM_CLIENT_LOG.ORGNO
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.ORGNO
     *
     * @param orgno the value for BO_CRM_CLIENT_LOG.ORGNO
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.BINDID
     *
     * @return the value of BO_CRM_CLIENT_LOG.BINDID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.BINDID
     *
     * @param bindid the value for BO_CRM_CLIENT_LOG.BINDID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.CREATEDATE
     *
     * @return the value of BO_CRM_CLIENT_LOG.CREATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.CREATEDATE
     *
     * @param createdate the value for BO_CRM_CLIENT_LOG.CREATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.CREATEUSER
     *
     * @return the value of BO_CRM_CLIENT_LOG.CREATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.CREATEUSER
     *
     * @param createuser the value for BO_CRM_CLIENT_LOG.CREATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.UPDATEDATE
     *
     * @return the value of BO_CRM_CLIENT_LOG.UPDATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_CLIENT_LOG.UPDATEDATE
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.UPDATEUSER
     *
     * @return the value of BO_CRM_CLIENT_LOG.UPDATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_CLIENT_LOG.UPDATEUSER
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.WORKFLOWID
     *
     * @return the value of BO_CRM_CLIENT_LOG.WORKFLOWID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_CLIENT_LOG.WORKFLOWID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_CLIENT_LOG.WORKFLOWSTEPID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_CLIENT_LOG.WORKFLOWSTEPID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.ISEND
     *
     * @return the value of BO_CRM_CLIENT_LOG.ISEND
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.ISEND
     *
     * @param isend the value for BO_CRM_CLIENT_LOG.ISEND
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.GSID
     *
     * @return the value of BO_CRM_CLIENT_LOG.GSID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getGsid() {
        return gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.GSID
     *
     * @param gsid the value for BO_CRM_CLIENT_LOG.GSID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setGsid(Object gsid) {
        this.gsid = gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.GSDM
     *
     * @return the value of BO_CRM_CLIENT_LOG.GSDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getGsdm() {
        return gsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.GSDM
     *
     * @param gsdm the value for BO_CRM_CLIENT_LOG.GSDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setGsdm(Object gsdm) {
        this.gsdm = gsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.GSMC
     *
     * @return the value of BO_CRM_CLIENT_LOG.GSMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getGsmc() {
        return gsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.GSMC
     *
     * @param gsmc the value for BO_CRM_CLIENT_LOG.GSMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setGsmc(Object gsmc) {
        this.gsmc = gsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.BMID
     *
     * @return the value of BO_CRM_CLIENT_LOG.BMID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getBmid() {
        return bmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.BMID
     *
     * @param bmid the value for BO_CRM_CLIENT_LOG.BMID
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setBmid(Object bmid) {
        this.bmid = bmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.BMMC
     *
     * @return the value of BO_CRM_CLIENT_LOG.BMMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.BMMC
     *
     * @param bmmc the value for BO_CRM_CLIENT_LOG.BMMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setBmmc(Object bmmc) {
        this.bmmc = bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.CZRZH
     *
     * @return the value of BO_CRM_CLIENT_LOG.CZRZH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getCzrzh() {
        return czrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.CZRZH
     *
     * @param czrzh the value for BO_CRM_CLIENT_LOG.CZRZH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setCzrzh(Object czrzh) {
        this.czrzh = czrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.CZRXM
     *
     * @return the value of BO_CRM_CLIENT_LOG.CZRXM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getCzrxm() {
        return czrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.CZRXM
     *
     * @param czrxm the value for BO_CRM_CLIENT_LOG.CZRXM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setCzrxm(Object czrxm) {
        this.czrxm = czrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.KHBH
     *
     * @return the value of BO_CRM_CLIENT_LOG.KHBH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getKhbh() {
        return khbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.KHBH
     *
     * @param khbh the value for BO_CRM_CLIENT_LOG.KHBH
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setKhbh(Object khbh) {
        this.khbh = khbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.KHMC
     *
     * @return the value of BO_CRM_CLIENT_LOG.KHMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.KHMC
     *
     * @param khmc the value for BO_CRM_CLIENT_LOG.KHMC
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setKhmc(Object khmc) {
        this.khmc = khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.WHSJ
     *
     * @return the value of BO_CRM_CLIENT_LOG.WHSJ
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Date getWhsj() {
        return whsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.WHSJ
     *
     * @param whsj the value for BO_CRM_CLIENT_LOG.WHSJ
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setWhsj(Date whsj) {
        this.whsj = whsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENT_LOG.WHLXDM
     *
     * @return the value of BO_CRM_CLIENT_LOG.WHLXDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public Object getWhlxdm() {
        return whlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENT_LOG.WHLXDM
     *
     * @param whlxdm the value for BO_CRM_CLIENT_LOG.WHLXDM
     *
     * @mbggenerated Tue Sep 11 10:40:04 CST 2018
     */
    public void setWhlxdm(Object whlxdm) {
        this.whlxdm = whlxdm;
    }
}