package cn.bravolinks.erp.crm.server.model.xzkh;

import java.math.BigDecimal;
import java.util.Date;

public class BoCrmClientbusOeve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.HZDW
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object hzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.LSSJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object lssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.XMRYGM
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object xmrygm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.XMJE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private BigDecimal xmje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.MDD
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object mdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.CBZT
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object cbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.XMKSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date xmksrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OEVE.XMJSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date xmjsrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.ID
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.ID
     *
     * @param id the value for BO_CRM_CLIENTBUS_OEVE.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.ORGNO
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.ORGNO
     *
     * @param orgno the value for BO_CRM_CLIENTBUS_OEVE.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.BINDID
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.BINDID
     *
     * @param bindid the value for BO_CRM_CLIENTBUS_OEVE.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.CREATEDATE
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.CREATEDATE
     *
     * @param createdate the value for BO_CRM_CLIENTBUS_OEVE.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.CREATEUSER
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.CREATEUSER
     *
     * @param createuser the value for BO_CRM_CLIENTBUS_OEVE.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.UPDATEDATE
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_CLIENTBUS_OEVE.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.UPDATEUSER
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_CLIENTBUS_OEVE.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWID
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_CLIENTBUS_OEVE.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_CLIENTBUS_OEVE.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.ISEND
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.ISEND
     *
     * @param isend the value for BO_CRM_CLIENTBUS_OEVE.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.HZDW
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.HZDW
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getHzdw() {
        return hzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.HZDW
     *
     * @param hzdw the value for BO_CRM_CLIENTBUS_OEVE.HZDW
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setHzdw(Object hzdw) {
        this.hzdw = hzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.LSSJ
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.LSSJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getLssj() {
        return lssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.LSSJ
     *
     * @param lssj the value for BO_CRM_CLIENTBUS_OEVE.LSSJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setLssj(Object lssj) {
        this.lssj = lssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.XMRYGM
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.XMRYGM
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getXmrygm() {
        return xmrygm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.XMRYGM
     *
     * @param xmrygm the value for BO_CRM_CLIENTBUS_OEVE.XMRYGM
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setXmrygm(Object xmrygm) {
        this.xmrygm = xmrygm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.XMJE
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.XMJE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public BigDecimal getXmje() {
        return xmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.XMJE
     *
     * @param xmje the value for BO_CRM_CLIENTBUS_OEVE.XMJE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setXmje(BigDecimal xmje) {
        this.xmje = xmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.MDD
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.MDD
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getMdd() {
        return mdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.MDD
     *
     * @param mdd the value for BO_CRM_CLIENTBUS_OEVE.MDD
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setMdd(Object mdd) {
        this.mdd = mdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.CBZT
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.CBZT
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getCbzt() {
        return cbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.CBZT
     *
     * @param cbzt the value for BO_CRM_CLIENTBUS_OEVE.CBZT
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setCbzt(Object cbzt) {
        this.cbzt = cbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.XMKSRQ
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.XMKSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getXmksrq() {
        return xmksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.XMKSRQ
     *
     * @param xmksrq the value for BO_CRM_CLIENTBUS_OEVE.XMKSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setXmksrq(Date xmksrq) {
        this.xmksrq = xmksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OEVE.XMJSRQ
     *
     * @return the value of BO_CRM_CLIENTBUS_OEVE.XMJSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getXmjsrq() {
        return xmjsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OEVE.XMJSRQ
     *
     * @param xmjsrq the value for BO_CRM_CLIENTBUS_OEVE.XMJSRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setXmjsrq(Date xmjsrq) {
        this.xmjsrq = xmjsrq;
    }
}