package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmIndclientbusYee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.LSSJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object lssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.FSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date fsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YEE.FSDD
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object fsdd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.ID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.ID
     *
     * @param id the value for BO_CRM_INDCLIENTBUS_YEE.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.ORGNO
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.ORGNO
     *
     * @param orgno the value for BO_CRM_INDCLIENTBUS_YEE.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.BINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.BINDID
     *
     * @param bindid the value for BO_CRM_INDCLIENTBUS_YEE.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.CREATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.CREATEDATE
     *
     * @param createdate the value for BO_CRM_INDCLIENTBUS_YEE.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.CREATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.CREATEUSER
     *
     * @param createuser the value for BO_CRM_INDCLIENTBUS_YEE.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_INDCLIENTBUS_YEE.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_INDCLIENTBUS_YEE.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_INDCLIENTBUS_YEE.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_INDCLIENTBUS_YEE.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.ISEND
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.ISEND
     *
     * @param isend the value for BO_CRM_INDCLIENTBUS_YEE.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.LSSJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.LSSJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getLssj() {
        return lssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.LSSJ
     *
     * @param lssj the value for BO_CRM_INDCLIENTBUS_YEE.LSSJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLssj(Object lssj) {
        this.lssj = lssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.FSRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.FSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getFsrq() {
        return fsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.FSRQ
     *
     * @param fsrq the value for BO_CRM_INDCLIENTBUS_YEE.FSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setFsrq(Date fsrq) {
        this.fsrq = fsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YEE.FSDD
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YEE.FSDD
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getFsdd() {
        return fsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YEE.FSDD
     *
     * @param fsdd the value for BO_CRM_INDCLIENTBUS_YEE.FSDD
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setFsdd(Object fsdd) {
        this.fsdd = fsdd;
    }
}