package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmClientbusOreg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.HGNR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object hgnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.FJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object fj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.TJR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Object tjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_CLIENTBUS_OREG.TJRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    private Date tjrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.ID
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.ID
     *
     * @param id the value for BO_CRM_CLIENTBUS_OREG.ID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.ORGNO
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.ORGNO
     *
     * @param orgno the value for BO_CRM_CLIENTBUS_OREG.ORGNO
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.BINDID
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.BINDID
     *
     * @param bindid the value for BO_CRM_CLIENTBUS_OREG.BINDID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.CREATEDATE
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.CREATEDATE
     *
     * @param createdate the value for BO_CRM_CLIENTBUS_OREG.CREATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.CREATEUSER
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.CREATEUSER
     *
     * @param createuser the value for BO_CRM_CLIENTBUS_OREG.CREATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.UPDATEDATE
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_CLIENTBUS_OREG.UPDATEDATE
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.UPDATEUSER
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_CLIENTBUS_OREG.UPDATEUSER
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWID
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_CLIENTBUS_OREG.WORKFLOWID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_CLIENTBUS_OREG.WORKFLOWSTEPID
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.ISEND
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.ISEND
     *
     * @param isend the value for BO_CRM_CLIENTBUS_OREG.ISEND
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.HGNR
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.HGNR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getHgnr() {
        return hgnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.HGNR
     *
     * @param hgnr the value for BO_CRM_CLIENTBUS_OREG.HGNR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setHgnr(Object hgnr) {
        this.hgnr = hgnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.FJ
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.FJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getFj() {
        return fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.FJ
     *
     * @param fj the value for BO_CRM_CLIENTBUS_OREG.FJ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setFj(Object fj) {
        this.fj = fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.TJR
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.TJR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Object getTjr() {
        return tjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.TJR
     *
     * @param tjr the value for BO_CRM_CLIENTBUS_OREG.TJR
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setTjr(Object tjr) {
        this.tjr = tjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_CLIENTBUS_OREG.TJRQ
     *
     * @return the value of BO_CRM_CLIENTBUS_OREG.TJRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public Date getTjrq() {
        return tjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_CLIENTBUS_OREG.TJRQ
     *
     * @param tjrq the value for BO_CRM_CLIENTBUS_OREG.TJRQ
     *
     * @mbggenerated Wed Sep 12 12:56:31 CST 2018
     */
    public void setTjrq(Date tjrq) {
        this.tjrq = tjrq;
    }
}