package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmIndclientbusYlm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.XB
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.GXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object gxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.DH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.SJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object sj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YLM.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.ID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.ID
     *
     * @param id the value for BO_CRM_INDCLIENTBUS_YLM.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.ORGNO
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.ORGNO
     *
     * @param orgno the value for BO_CRM_INDCLIENTBUS_YLM.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.BINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.BINDID
     *
     * @param bindid the value for BO_CRM_INDCLIENTBUS_YLM.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.CREATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.CREATEDATE
     *
     * @param createdate the value for BO_CRM_INDCLIENTBUS_YLM.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.CREATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.CREATEUSER
     *
     * @param createuser the value for BO_CRM_INDCLIENTBUS_YLM.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_INDCLIENTBUS_YLM.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_INDCLIENTBUS_YLM.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_INDCLIENTBUS_YLM.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_INDCLIENTBUS_YLM.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.ISEND
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.ISEND
     *
     * @param isend the value for BO_CRM_INDCLIENTBUS_YLM.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.XM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.XM
     *
     * @param xm the value for BO_CRM_INDCLIENTBUS_YLM.XM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXm(Object xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.XB
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.XB
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.XB
     *
     * @param xb the value for BO_CRM_INDCLIENTBUS_YLM.XB
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setXb(Object xb) {
        this.xb = xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.GXDM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.GXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getGxdm() {
        return gxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.GXDM
     *
     * @param gxdm the value for BO_CRM_INDCLIENTBUS_YLM.GXDM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setGxdm(Object gxdm) {
        this.gxdm = gxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.DH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.DH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.DH
     *
     * @param dh the value for BO_CRM_INDCLIENTBUS_YLM.DH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDh(Object dh) {
        this.dh = dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.SJ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.SJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.SJ
     *
     * @param sj the value for BO_CRM_INDCLIENTBUS_YLM.SJ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setSj(Object sj) {
        this.sj = sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.CSRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.CSRQ
     *
     * @param csrq the value for BO_CRM_INDCLIENTBUS_YLM.CSRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YLM.BZ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YLM.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YLM.BZ
     *
     * @param bz the value for BO_CRM_INDCLIENTBUS_YLM.BZ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBz(Object bz) {
        this.bz = bz;
    }
}