package cn.bravolinks.erp.crm.server.model.xzkh;

import java.util.Date;

public class BoCrmIndclientbusYtr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer workflowstepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Integer isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.GZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.SZBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object szbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object dwdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.ZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.ZYLY
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Object zyly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.RZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date rzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BO_CRM_INDCLIENTBUS_YTR.LZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    private Date lzrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.ID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.ID
     *
     * @param id the value for BO_CRM_INDCLIENTBUS_YTR.ID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.ORGNO
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.ORGNO
     *
     * @param orgno the value for BO_CRM_INDCLIENTBUS_YTR.ORGNO
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setOrgno(Object orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.BINDID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.BINDID
     *
     * @param bindid the value for BO_CRM_INDCLIENTBUS_YTR.BINDID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.CREATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.CREATEDATE
     *
     * @param createdate the value for BO_CRM_INDCLIENTBUS_YTR.CREATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.CREATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.CREATEUSER
     *
     * @param createuser the value for BO_CRM_INDCLIENTBUS_YTR.CREATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setCreateuser(Object createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEDATE
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEDATE
     *
     * @param updatedate the value for BO_CRM_INDCLIENTBUS_YTR.UPDATEDATE
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEUSER
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.UPDATEUSER
     *
     * @param updateuser the value for BO_CRM_INDCLIENTBUS_YTR.UPDATEUSER
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setUpdateuser(Object updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWID
     *
     * @param workflowid the value for BO_CRM_INDCLIENTBUS_YTR.WORKFLOWID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWSTEPID
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getWorkflowstepid() {
        return workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.WORKFLOWSTEPID
     *
     * @param workflowstepid the value for BO_CRM_INDCLIENTBUS_YTR.WORKFLOWSTEPID
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setWorkflowstepid(Integer workflowstepid) {
        this.workflowstepid = workflowstepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.ISEND
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.ISEND
     *
     * @param isend the value for BO_CRM_INDCLIENTBUS_YTR.ISEND
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.GZDW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.GZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.GZDW
     *
     * @param gzdw the value for BO_CRM_INDCLIENTBUS_YTR.GZDW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setGzdw(Object gzdw) {
        this.gzdw = gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.SZBM
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.SZBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getSzbm() {
        return szbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.SZBM
     *
     * @param szbm the value for BO_CRM_INDCLIENTBUS_YTR.SZBM
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setSzbm(Object szbm) {
        this.szbm = szbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.DWDH
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getDwdh() {
        return dwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.DWDH
     *
     * @param dwdh the value for BO_CRM_INDCLIENTBUS_YTR.DWDH
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setDwdh(Object dwdh) {
        this.dwdh = dwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.ZW
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.ZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.ZW
     *
     * @param zw the value for BO_CRM_INDCLIENTBUS_YTR.ZW
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZw(Object zw) {
        this.zw = zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.ZYLY
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.ZYLY
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Object getZyly() {
        return zyly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.ZYLY
     *
     * @param zyly the value for BO_CRM_INDCLIENTBUS_YTR.ZYLY
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setZyly(Object zyly) {
        this.zyly = zyly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.RZRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.RZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getRzrq() {
        return rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.RZRQ
     *
     * @param rzrq the value for BO_CRM_INDCLIENTBUS_YTR.RZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setRzrq(Date rzrq) {
        this.rzrq = rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BO_CRM_INDCLIENTBUS_YTR.LZRQ
     *
     * @return the value of BO_CRM_INDCLIENTBUS_YTR.LZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public Date getLzrq() {
        return lzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BO_CRM_INDCLIENTBUS_YTR.LZRQ
     *
     * @param lzrq the value for BO_CRM_INDCLIENTBUS_YTR.LZRQ
     *
     * @mbggenerated Fri Sep 21 14:49:32 CST 2018
     */
    public void setLzrq(Date lzrq) {
        this.lzrq = lzrq;
    }
}